import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import {ChangelogContextProvider} from "../context/changelog";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Changelog Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ChangelogContextProvider>
          <Navbar />
          <div>
            {children}
          </div>
        </ChangelogContextProvider>
      </body>
    </html>
  );
}
